# Generated by Django 2.2.3 on 2019-09-11 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrumuser',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='account.Company'),
        ),
    ]
