# Generated by Django 2.2.3 on 2019-09-22 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_scrumuser_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrumuser',
            name='company',
        ),
    ]
