# Generated by Django 2.2.3 on 2019-09-16 14:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('daudonmailscrumy', '0002_user'),
    ]

    # operations = [
    #     migrations.CreateModel(
    #         name='Project',
    #         fields=[
    #             ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
    #             ('title', models.CharField(max_length=50)),
    #             ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
    #         ],
    #     ),
    # ]
