# Generated by Django 2.2.3 on 2019-09-16 14:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daudonmailscrumy', '0003_project'),
    ]

    # operations = [
    #     migrations.AlterField(
    #         model_name='project',
    #         name='user',
    #         field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
    #     ),
    # ]
