# Generated by Django 2.2.3 on 2019-09-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daudonmailscrumy', '0005_scrumygoals_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.CharField(default='louis', max_length=100),
        ),
    ]
